version: '3.4'

services:
  server:
    image: server
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app/
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
